app_home:
    path: /
    controller: App\Controller\HomeController::showHome

app_trick:
    path: /figure
    controller: App\Controller\TrickController::showTrick

# app_register:
#     path: /inscription
#     controller: App\Controller\RegistrationController::register