home:
    path: /
    controller: App\Controller\HomeController::showHome

trick:
    path: /trick
    controller: App\Controller\TrickController::showTrick

register:
    path: /register
    controller: App\Controller\UserController::showRegister