index:
    path: /
    controller: App\Controller\IndexController::showIndex

trick:
    path: /trick
    controller: App\Controller\TrickController::showTrick

register:
    path: /register
    controller: App\Controller\UserController::showRegister